config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'pages#index'
  get 'messenger', to: 'messengers#index'
  get 'get_private_conversation', to: 'messengers#get_private_conversation'
  get 'get_group_conversation', to: 'messengers#get_group_conversation'
  get 'open_messenger', to: 'messengers#open_messenger'

  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end

  namespace :private do 
    resources :conversations, only: [:create] do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: [:index, :create]
  end

  namespace :group do 
    resources :conversations do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: [:index, :create]
  end

  resources :contacts, only: [:create, :update, :destroy]

end

app/helpers/navigation_helper.rb
module NavigationHelper

  # return a conversation header partial's path
  def conversation_header_partial_path(conversation)
    if conversation.class == Private::Conversation
      'layouts/navigation/header/dropdowns/conversations/private'
    else
      'layouts/navigation/header/dropdowns/conversations/group'
    end  
  end

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

  # render the navigation header's content
  def nav_header_content_partials
    partials = []
    if params[:controller] == 'messengers' 
      partials << 'layouts/navigation/header/messenger_header'
    else # controller is not messengers  
      partials << 'layouts/navigation/header/toggle_button'
      partials << 'layouts/navigation/header/home_button'
      partials << 'layouts/navigation/header/dropdowns' if user_signed_in?
    end
    partials
  end

  def nav_contact_requests_partial_path
    # if contact requests exist
    if current_user.pending_received_contact_requests.present? 
      'layouts/navigation/header/dropdowns/contact_requests/requests' 
    else # contact requests do not exist 
      'layouts/navigation/header/dropdowns/contact_requests/no_requests'
    end
  end

end

app/views/layouts/navigation/collapsible_elements/_constant_links.html.erb
<li class="mobile-menu">
  <ul>
    <li>
      <%= link_to hobby_posts_path do %>
        <i class="fa fa-user-circle-o" aria-hidden="true"></i> Find a hobby buddy
      <% end %>
    </li>
    <li>
      <%= link_to study_posts_path do %>
        <i class="fa fa-graduation-cap" aria-hidden="true"></i> Find a study buddy
      <% end %>
    </li>
    <li>
      <%= link_to team_posts_path do %>
        <i class="fa fa-users" aria-hidden="true"></i> Find a team member
      <% end %>
    </li>
    <li>
      <%= link_to messenger_path, class: 'messenger-link' do %>
        <i class="fa fa-envelope" aria-hidden="true"></i> Messages
      <% end %>
    </li>
  </ul>
</li><!-- mobile_menu --> 

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li><%= link_to 'Login', login_path %></li>
<li><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>
</li>

<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>